# -*- coding: utf-8 -*-
"""
BẢNG CẤU HÌNH & ÁNH XẠ 25 DỰ ÁN TRƯỜNG LIÊN CẤP PHỐ BẢNG
Hệ thống Multi-Agent AEC (23HG-multiagent-system).
"""
import datetime
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any


@dataclass
class ProjectDefinition:
    folder_name: str
    short_name: str
    full_name: str
    project_type: str
    start_date: datetime.date
    finish_date: datetime.date
    hm_code: Optional[str] = None
    qlcl_filename: Optional[str] = None
    priority_level: int = 1


PROJECTS_PHO_BANG: List[ProjectDefinition] = [
    ProjectDefinition(
        folder_name="1. Ký túc xá nữ THCS (Nhà số 13)ok_Marker",
        short_name="KTX_Nu_THCS_Nha13",
        full_name="Nhà số 13: Ký túc xá nữ THCS (Diện tích XD 1081.3m2)",
        project_type="civil",
        start_date=datetime.date(2026, 3, 1),
        finish_date=datetime.date(2026, 10, 30),
        hm_code="HM02",
        qlcl_filename=None,
    ),
    ProjectDefinition(
        folder_name="10. Cải tạo nhà 3 tầng thành nhà hiệu bộ và chức năng (Nhà số 3)_Marker",
        short_name="Cai_Tao_Hieu_Bo_Nha03",
        full_name="Nhà số 03: Cải tạo nhà 3 tầng thành nhà hiệu bộ và chức năng",
        project_type="civil_renovation",
        start_date=datetime.date(2026, 3, 15),
        finish_date=datetime.date(2026, 8, 30),
        hm_code="HM11",
        qlcl_filename="HO_SO_QLCL_NHA_SO_03_TIENG_VIET_CO_DAU.xlsx",
    ),
    ProjectDefinition(
        folder_name="2. Khu học thông thường khối tiểu học (Nhà số 4)ok_Marker",
        short_name="Khu_Hoc_Tieu_Hoc_Nha04",
        full_name="Nhà số 4: Khu học thông thường khối tiểu học (572.5m2)",
        project_type="civil",
        start_date=datetime.date(2026, 3, 1),
        finish_date=datetime.date(2026, 9, 30),
        hm_code="HM03",
        qlcl_filename="Du_Toan_Tien_Do_Nha_So_4.xlsx",
    ),
    ProjectDefinition(
        folder_name="3. Ký túc xá nữ TH (Nhà số 14) ok_Marker",
        short_name="KTX_Nu_TH_Nha14",
        full_name="Nhà số 14: Ký túc xá nữ tiểu học (521m2)",
        project_type="civil",
        start_date=datetime.date(2026, 3, 1),
        finish_date=datetime.date(2026, 9, 30),
        hm_code="HM04",
        qlcl_filename="Ho_So_QLCL_KTX_Nu_TH_Nha14.xlsx",
    ),
    ProjectDefinition(
        folder_name="4. Ký túc xá nam TH (Nhà số 15)ok_Marker",
        short_name="KTX_Nam_TH_Nha15",
        full_name="Nhà số 15: Ký túc xá nam tiểu học (581.3m2)",
        project_type="civil",
        start_date=datetime.date(2026, 3, 1),
        finish_date=datetime.date(2026, 9, 30),
        hm_code="HM05",
        qlcl_filename="Ho_So_QLCL_KTX_Nam_TH_Nha15.xlsx",
    ),
    ProjectDefinition(
        folder_name="5. Cải tạo Nhà bếp ăn (Nhà 17và 17A) ok_Marker",
        short_name="Nha_Bep_An_17_17A",
        full_name="Nhà số 17 và 17A: Cải tạo nhà bếp ăn và bếp xây mới",
        project_type="civil_renovation",
        start_date=datetime.date(2026, 10, 1),
        finish_date=datetime.date(2026, 11, 30),
        hm_code="HM06",
        qlcl_filename="Ho_So_QLCL_NhaBepAn_Nha17_17A.xlsx",
    ),
    ProjectDefinition(
        folder_name="6. Cải tạo nhà ở ký túc xá tiểu học (Nhà số 23) ok_Marker",
        short_name="Cai_Tao_KTX_TH_Nha23",
        full_name="Nhà số 23: Cải tạo nhà UBND thành Ký túc xá Tiểu học",
        project_type="civil_renovation",
        start_date=datetime.date(2026, 3, 15),
        finish_date=datetime.date(2026, 9, 15),
        hm_code="HM07",
        qlcl_filename="Ho_So_QLCL_KTX_TieuHoc_Nha23.xlsx",
    ),
    ProjectDefinition(
        folder_name="7. Khu học bộ môn liên cấp TH & THCS 3 tầng (Nhà số 5+7) ok_Marker",
        short_name="Khu_Hoc_Bo_Mon_Nha5_7",
        full_name="Nhà số 5+7: Khu học bộ môn liên cấp TH & THCS 3 tầng (767.5m2)",
        project_type="civil",
        start_date=datetime.date(2026, 3, 1),
        finish_date=datetime.date(2026, 10, 15),
        hm_code="HM08",
        qlcl_filename="Ho_So_QLCL_KhuHocBoMon_Nha5_7.xlsx",
    ),
    ProjectDefinition(
        folder_name="8. Ký túc xá giáo viên (Nhà số 11) ok_Marker",
        short_name="KTX_Giao_Vien_Nha11",
        full_name="Nhà số 11: Ký túc xá giáo viên (458.12m2)",
        project_type="civil",
        start_date=datetime.date(2026, 6, 15),
        finish_date=datetime.date(2026, 11, 15),
        hm_code="HM09",
        qlcl_filename=None,
    ),
    ProjectDefinition(
        folder_name="9. Bể xử lý nước thải Bastaf (02CK) ok_Marker",
        short_name="Be_Xu_Ly_Nuoc_Thai_Bastaf",
        full_name="Bể xử lý nước thải Bastaf (02CK)",
        project_type="infra_water",
        start_date=datetime.date(2026, 4, 1),
        finish_date=datetime.date(2026, 7, 30),
        hm_code="HM10",
        qlcl_filename="HO_SO_QLCL_BE_BASTAF_TIENG_VIET_CO_DAU.xlsx",
    ),
    ProjectDefinition(
        folder_name="Các dãy nhà phá dỡ_Marker",
        short_name="Cac_Day_Nha_Pha_Do",
        full_name="Phá dỡ các dãy nhà cũ hiện trạng",
        project_type="demolition",
        start_date=datetime.date(2026, 2, 15),
        finish_date=datetime.date(2026, 4, 15),
        hm_code=None,
        qlcl_filename="HO_SO_QLCL_CAC_DAY_NHA_PHA_DO_TIENG_VIET_CO_DAU.xlsx",
    ),
    ProjectDefinition(
        folder_name="Cải tạo nhà lớp học 2 tầng 8 phòng học (Nhà số 6A1)_Marker",
        short_name="Cai_Tao_Lop_Hoc_Nha6A1",
        full_name="Nhà số 6A1: Cải tạo nhà lớp học 02 tầng 08 phòng học",
        project_type="civil_renovation",
        start_date=datetime.date(2026, 4, 1),
        finish_date=datetime.date(2026, 8, 30),
        hm_code="HM12",
        qlcl_filename="HO_SO_QLCL_NHA_SO_6A1_TIENG_VIET_CO_DAU.xlsx",
    ),
    ProjectDefinition(
        folder_name="Cải tạo nhà lớp học 2 tầng thành nhà chức năng (Nhà số 3A)_Marker",
        short_name="Cai_Tao_Chuc_Nang_Nha3A",
        full_name="Nhà số 3A: Cải tạo nhà lớp học 02 tầng thành nhà chức năng",
        project_type="civil_renovation",
        start_date=datetime.date(2026, 4, 1),
        finish_date=datetime.date(2026, 8, 30),
        hm_code="HM13",
        qlcl_filename="HO_SO_QLCL_NHA_SO_3A_TIENG_VIET_CO_DAU.xlsx",
    ),
    ProjectDefinition(
        folder_name="Cấp nước sinh hoạt đầu nguồn_Marker",
        short_name="Cap_Nuoc_Sinh_Hoat_Dau_Nguon",
        full_name="Hệ thống cấp nước sinh hoạt đầu nguồn",
        project_type="infra_water",
        start_date=datetime.date(2026, 3, 1),
        finish_date=datetime.date(2026, 6, 30),
        hm_code=None,
        qlcl_filename="HO_SO_QLCL_CAP_NUOC_DAU_NGUON_TIENG_VIET_CO_DAU.xlsx",
    ),
    ProjectDefinition(
        folder_name="Cấp thoát nước_Marker",
        short_name="Cap_Thoat_Nuoc",
        full_name="Hệ thống cấp thoát nước ngoài nhà và bể tự hoại",
        project_type="infra_water",
        start_date=datetime.date(2026, 4, 1),
        finish_date=datetime.date(2026, 9, 30),
        hm_code="HM32",
        qlcl_filename="HO_SO_QLCL_CAP_THOAT_NUOC_TIENG_VIET_CO_DAU.xlsx",
    ),
    ProjectDefinition(
        folder_name="Hệ thống đèn chiếu sáng sân đường nội bộ_Marker",
        short_name="He_Thong_Chieu_Sang_Noi_Bo",
        full_name="Hệ thống đèn chiếu sáng sân đường nội bộ",
        project_type="infra_electric",
        start_date=datetime.date(2026, 6, 1),
        finish_date=datetime.date(2026, 9, 30),
        hm_code=None,
        qlcl_filename="HO_SO_QLCL_DEN_CHIEU_SANG_TIENG_VIET_CO_DAU.xlsx",
    ),
    ProjectDefinition(
        folder_name="Khu học thông thường 2 phòng học (Nhà số 6A)_Marker",
        short_name="Khu_Hoc_2_Phong_Nha6A",
        full_name="Nhà số 6A: Khu học thông thường 02 phòng học",
        project_type="civil",
        start_date=datetime.date(2026, 3, 15),
        finish_date=datetime.date(2026, 8, 30),
        hm_code=None,
        qlcl_filename="HO_SO_QLCL_NHA_SO_6A_TIENG_VIET_CO_DAU.xlsx",
    ),
    ProjectDefinition(
        folder_name="Khu học thông thường khối TH (Nhà số 6)_Marker",
        short_name="Khu_Hoc_Khoi_TH_Nha06",
        full_name="Nhà số 6: Khu học thông thường khối tiểu học",
        project_type="civil",
        start_date=datetime.date(2026, 3, 15),
        finish_date=datetime.date(2026, 8, 30),
        hm_code=None,
        qlcl_filename="HO_SO_QLCL_NHA_SO_06_TIENG_VIET_CO_DAU.xlsx",
    ),
    ProjectDefinition(
        folder_name="Ký túc xá nam THCS  (Nhà số 12)_Marker",
        short_name="KTX_Nam_THCS_Nha12",
        full_name="Nhà số 12: Ký túc xá nam THCS",
        project_type="civil",
        start_date=datetime.date(2026, 3, 1),
        finish_date=datetime.date(2026, 10, 15),
        hm_code="HM14",
        qlcl_filename="HO_SO_QLCL_NHA_SO_12_TIENG_VIET_CO_DAU.xlsx",
    ),
    ProjectDefinition(
        folder_name="Nhà thi đấu đa năng (Nhà số 8)_Marker",
        short_name="Nha_Thi_Dau_Da_Nang_Nha08",
        full_name="Nhà số 8: Nhà thi đấu đa năng (30x36m, diện tích sàn 651.88m2)",
        project_type="civil_large_span",
        start_date=datetime.date(2026, 4, 1),
        finish_date=datetime.date(2026, 11, 15),
        hm_code="HM15",
        qlcl_filename="Ho_So_QLCL_Nha_Thi_Dau_Da_Nang_Nha_So_8.xlsx",
    ),
    ProjectDefinition(
        folder_name="San nền_Marker",
        short_name="San_Nen_Khu1_Khu2",
        full_name="Thi công san nền khu 1 và khu 2",
        project_type="infra_earthwork",
        start_date=datetime.date(2026, 2, 15),
        finish_date=datetime.date(2026, 6, 15),
        hm_code="HM16",
        qlcl_filename=None,
    ),
    ProjectDefinition(
        folder_name="Sân bóng đá ( số 9)_Marker",
        short_name="San_Bong_Da_So09",
        full_name="Hạng mục: Sân bóng đá (số 9)",
        project_type="sports_field",
        start_date=datetime.date(2026, 5, 1),
        finish_date=datetime.date(2026, 9, 30),
        hm_code="HM37",
        qlcl_filename=None,
    ),
    ProjectDefinition(
        folder_name="Tổng mặt bằng, Cổng hàng rào, kè đá, cột cờ…_Marker",
        short_name="Tong_Mat_Bang_Hang_Rao_Ke_Da",
        full_name="Tổng mặt bằng, Cổng hàng rào, kè đá xây, cột cờ",
        project_type="infra_landscape",
        start_date=datetime.date(2026, 4, 15),
        finish_date=datetime.date(2026, 10, 30),
        hm_code="HM19",
        qlcl_filename=None,
    ),
    ProjectDefinition(
        folder_name="Đường dây 35 Kv, trạm biến áp và đường dây 0,4Kv_Marker",
        short_name="Duong_Day_35kV_Tram_Bien_Ap",
        full_name="Đường dây 35kV, trạm biến áp và đường dây 0,4kV",
        project_type="infra_electric",
        start_date=datetime.date(2026, 5, 15),
        finish_date=datetime.date(2026, 9, 30),
        hm_code=None,
        qlcl_filename=None,
    ),
    ProjectDefinition(
        folder_name="Đường giao thông_Marker",
        short_name="Duong_Giao_Thong_Noi_Bo",
        full_name="Nền đường, mặt đường và cống thoát nước giao thông",
        project_type="infra_road",
        start_date=datetime.date(2026, 3, 1),
        finish_date=datetime.date(2026, 8, 30),
        hm_code="HM18",
        qlcl_filename="HO_SO_QLCL_DUONG_GIAO_THONG_TIENG_VIET_CO_DAU.xlsx",
    ),
    ProjectDefinition(
        folder_name="Cầu thôn Khai Hoang 2, Km 14+363.65_Marker_2",
        short_name="Cau_Khai_Hoang_2",
        full_name="Cầu thôn Khai Hoang 2, Km 14+363.65 (Nhịp dầm T L=15m, Mố BTCT)",
        project_type="bridge",
        start_date=datetime.date(2026, 3, 1),
        finish_date=datetime.date(2026, 7, 31)
    )
]
